name: Deploy to Development Server

on:
  push:
    branches:
      - Development  # Runs on Development branch push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.KC_DEVELOPMENT_SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        # Add EC2 IP to known_hosts
        ssh-keyscan 15.206.211.84 >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

        # SSH into EC2 and execute deployment commands
        ssh -o StrictHostKeyChecking=no ec2-user@15.206.211.84 << 'EOF'
          echo "Switching to project directory..."
          cd ~/Diskuss || git clone -b Development https://github.com/YOUR_REPO.git ~/Diskuss && cd ~/Diskuss

          echo "Checking out Development branch..."
          git checkout Development
          git pull origin Development

          echo "Installing dependencies..."
          npm install --production

          echo "Restarting application..."
          pm2 reload all || pm2 start server.js

          echo "Deployment to Development server completed!"
        EOF

    - name: Complete Deployment
      run: echo "Development Deployment successful!"
