name: Deploy to Development Server

on:
  push:
    branches:
      - Development  # Runs on Development branch push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.KC_DEVELOPMENT_SSH_PRIVATE_KEY }}

    - name: Deploy to EC2 (Development)
      run: |
        ssh-keyscan 3.7.254.117 >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

        ssh -o StrictHostKeyChecking=no ec2-user@3.7.254.117 << 'EOF'
          cd ~/Diskuss || git clone -b Development https://github.com/YOUR_REPO.git ~/Diskuss && cd ~/Diskuss
          git checkout Development
          git pull origin Development

          npm install --production
          pm2 reload all || pm2 start server.js

          echo "Deployment to Development server completed!"
        EOF
